version: '3'
services:
  consul:
    image: "consul:1.10"
    hostname: "consul"
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - ./config/consul:/config
      - ./certs:/certs
  vault:
    depends_on:
      - consul
    image: "vault:1.8.3"
    hostname: "vault"
    links:
      - "consul:consul"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./config/vault:/config:z
      - ./certs:/certs:z
      - ./tools/wait-for-it.sh:/wait-for-it.sh:z
      - ./config/vault/policies:/policies:z
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/vault.hcl

